### ISSUE TITLE
Retire

### ISSUE THREAD

**Issue by Ms2ger** [Manishearth/rust-tenacious#20]
This crate is not going to work with MIR, and its use case in Servo has been removed.

**Comment by Manishearth** [comment]
Any idea how I should go about retiring it? Simple edit to the readme/description?

**Comment by Ms2ger** [comment]
That sounds good enough to me.

**Comment by Manishearth** [comment]
Done. Might be revived in the future as a MIR plugin, since this crate is useful for bindings to C++ intrusive datatypes.
